### ISSUE TITLE
refactor: Plugin naming schema update

### ISSUE THREAD

**Issue by eaglesemanation** [solo-io/packer-plugin-arm-image#108]
Packer updated their [naming schema](https://www.packer.io/docs/plugins/creation#creating-a-github-release) for plugins, and now it should be prefixed with `packer-plugin-`, for example `packer-plugin-arm-image`. While it may be a breaking change, it comes from upstream, so I think it should be followed.

**Comment by yuval-k** [comment]
fixed by #109
