### ISSUE TITLE
Update to packer-sdc command for validating plugin compatibility

### ISSUE THREAD

**Issue by nywilken** [solo-io/packer-plugin-arm-image#128]
👋 Fellow Packer maintainer here,  reaching out to inform you about an upcoming breaking change that will affect your goreleaser release pipeline. In Packer 1.8.0 we will remove the [`packer-plugin-check`](github.com/hashicorp/packer/cmd/packer-plugins-check) command in Packer core in favor of the [`packer-sdc plugin-check`](https://github.com/hashicorp/packer-plugin-sdk/cmd/packer-sdc) command from the [Packer Plugin SDK](https://github.com/hashicorp/packer-plugin-sdk/tree/main/cmd/packer-sdc). So calling `go install github.com/hashicorp/packer/cmd/packer-plugins-check@latest` will result in an error. 

To avoid potential issues I recommend either pinning the `packer-plugins-check` command to the current version of Packer until you can move to the `packer-sdc` command

`go install github.com/hashicorp/packer/cmd/packer-plugins-check@v1.7.10` 

Or you can update your release configuration to use the `packer-sdc` command, which is the preferred long-term solution. 

I'v provided a link to the updates that were made to the Packer Plugin Scaffolding for using the `packer-sdc` command [here](https://github.com/hashicorp/packer-plugin-scaffolding/pull/63/files#diff-42e26dc67aed8aa3edb2472b4403288c1699fb6dc47419b9a475f0f224fe4689)

Please let me know if you have any questions.

**Comment by yuval-k** [comment]
thank you!
