### ISSUE TITLE
Contribute Cloud-Init + Ubuntu 20.04/22.04 Samples to Repository

### ISSUE THREAD

**Issue by shantanoo-desai** [solo-io/packer-plugin-arm-image#148]
## Description

[Cloud-Init](https://cloud-init.io) is now a _standard_ in terms of setting up devices in the cloud and cloud-native capable hardware (raspberry pis etc.) on first boot.

This repository currently doesn't have any examples for how and where to introduce the `cloud-init` files in the Images for Raspberry Pis.

I have been able to figure out the way to combine Packer w/ this plugin + cloud-init for Ubuntu 20.04/22.04 for Raspberry Pis (albeit not in docker containers, but locally) to create such custom images

There is currently no Contributing guideline so I want to know if there are some prerequisites to contributing this example and how should it be structured.

**Comment by yuval-k** [comment]
it's pretty ad-hoc;  we have a bunch of samples in here: https://github.com/solo-io/packer-plugin-arm-image/tree/master/samples
feel free to add a folder there with your example, and a paragraph in the readme under the samples folder?

Thank you very much for your contribution!
